### PR TITLE
beautify readme, add complete instructions

### PR DESCRIPTION
**Pull request by acxz**
From my experience of setting things up, I updated the readme. Hopefully it is more helpful and also looks a bit better ;)

Take a look at [`readme/README.md`](https://github.com/stevesdawg/govstat/blob/readme/README.md) for how it looks in md.

### CODE REVIEW

**Comment by acxz** [comment]
Only thing I'm a bit iffy on is using `usc-run` before the python-package PR to congress is merged. But I think it's fine as otherwise we would have to add instructions on cloning congress. Feel free to add or remove content as you see fit, tho.

**Review by sseshan7 — APPROVED** [review]
This is excellent! I'm okay with keeping the `usc-run` commands in, I'm hopeful it will get merged into `congress`.

A todo for me is to add sample values to the `config.sample.json` file.

This looks good to merge though.

**Comment by acxz** [comment]
> A todo for me is to add sample values to the `config.sample.json` file.

See: #22 

Although I just put in mariadb based URI since that is what I use. Considering the instructions suggest mariadb that is prob fine.

**Comment by acxz** [comment]
> This is excellent! I'm okay with keeping the usc-run commands in, I'm hopeful it will get merged into congress.

One thing I just realized, even if the python-package branch at congress gets merged in, it won't be on `pypi` so users will still have to manually download and install `congress`, which we should mention in the readme.

**Comment by sseshan7** [comment]
Ah yes, covered in #22 !

**Pull request merged**
